---
# tasks file for deploy_apache
- name: Check Linux distro
  debug: var=ansible_os_family

- block: #For Debian

  - name: Install Python-pip
    apt: name=python state=latest

  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Start Apache and enable it during boot
    service: name=apache2 state=started enabled=yes

  - name: Update Apache default conf  file
    template: src=location.conf dest=/etc/apache2/sites-available/000-default.conf
    notify: Restart Apache Debian

    when: ansible_os_family == "Debian"
